### ISSUE TITLE
вопрос по интеграции

### ISSUE THREAD

**Issue by Yarprogress** [gietos/dadata#2]
Добрый день. пытаюсь понять как применить этот модуль в моем проекте. Насколько я понимаю он внедряется в контроллер (мне нужно при сохрании формы с данными о человеке автоматически исправлять в ФИО, телефоне и т.д. ошибки и сохранять в базу уже корректный вариант. Верно ли это и можно ли попросить помочь?

**Comment by gietos** [comment]
Я бы дал пользователю возможность перед сохранением проверить исправленный вариант.
Например, при потере полем фокуса делать AJAX-запрос к контроллеру и показывать предупреждение, если данные были исправлены. 

Например, как это сделано в Достависте:

<img width="364" alt="screen shot 2016-09-28 at 15 17 42" src="https://cloud.githubusercontent.com/assets/490653/18913136/d96c9f3c-858e-11e6-8f17-18b6169f9207.png">

**Comment by Yarprogress** [comment]
хороший вариант, это получается ajax запрос в форме будет по потере фокуса?

**Comment by gietos** [comment]
Конкретно в моем примере это сделано на вставку из буфера. Но в своей форме вам решать.
