### ISSUE TITLE
Не все возвращаемые поля есть в классе Address

### ISSUE THREAD

**Issue by Rastishka** [gietos/dadata#3]
В документации есть https://dadata.ru/api/clean/, а в абстрактном классе Address нет полей:

public $region_fias_id;
public $region_kladr_id;
public $region_with_type;
public $area_fias_id;
public $area_kladr_id;
public $area_with_type;
public $city_fias_id;
public $city_kladr_id;
public $city_with_type;
public $city_area;
public $city_district_fias_id;
public $city_district_kladr_id;
public $city_district_with_type;
public $city_district_type;
public $city_district_type_full;
public $settlement_fias_id;
public $settlement_kladr_id;
public $settlement_with_type;
public $street_fias_id;
public $street_kladr_id;
public $street_with_type;
public $house_fias_id;
public $house_kladr_id;

Особенно расстраивает отсутствие city_area

**Comment by gietos** [comment]
@Rastishka, спасибо!
