### ISSUE TITLE
Некорректно отдается number в стандартизации номера телефона

### ISSUE THREAD

**Issue by alexmorbo** [gietos/dadata#34]
Наткнулся на проблему при стандартизации номера телефона.
Если смотреть, что отдает стандартизация от дадаты по номеру телефона, то получаю следующее:
```
array:12 [
  "source" => "79920073931"
  "type" => "Мобильный"
  "phone" => "+7 992 007-39-31"
  "country_code" => "7"
  "city_code" => "992"
  "number" => "0073931"
  "extension" => null
  "provider" => "ООО "Т2 Мобайл""
  "region" => "Свердловская область"
  "timezone" => "UTC+5"
  "qc_conflict" => 0
  "qc" => 0
]
```

После того, как ответ от дадаты обрабатывается библиотекой, то получаю следующее:
```
Dadata\Response\Phone {#83
  +source: "79920073931"
  +type: "Мобильный"
  +phone: "+7 992 007-39-31"
  +country_code: 7
  +city_code: 992
  +number: 73931
  +extension: null
  +provider: "ООО "Т2 Мобайл""
  +region: "Свердловская область"
  +timezone: "UTC+5"
  +qc_conflict: 0
  +qc: 0
}
```

Как видно, поле number - имеет int'овое значение, нули обрезаются и если обращаться к этому полю, то финальный номер будет некорректен.

Лечится, если привести это поле к string типу

**Comment by gietos** [comment]
Thanks, @alexmorbo!
Fixed in version 1.1.14

**Comment by gietos** [comment]
Oh, i'm sorry. Merged wrong branch. 1.1.14 is broken, use 1.1.15
@alexmorbo
