### ISSUE TITLE
Argument 1 passed to Dadata\Client in Laravel

### ISSUE THREAD

**Issue by ermilov** [gietos/dadata#42]
Во время выполнения composer install получаю следующую ошибку: 
                                                                      
```
Illuminate\Foundation\ComposerScripts::postAutoloadDump
>@php artisan package:discover --ansi

In Client.php line 78:

  Argument 1 passed to Dadata\Client::__construct() must be an instance of Gu  
  zzleHttp\ClientInterface, instance of Illuminate\Foundation\Application giv  
  en, called in /home/domain.com/api/www/vendor/laravel/framework/src/Illumina  
  te/Foundation/ProviderRepository.php on line 208     
```

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

>php artisan package:discover --ansi

```
Argument 1 passed to Dadata\Client::__construct() must be an instance of GuzzleHttp\ClientInterface, instance of Illuminate\Foundation\Application given, called in   
  /home/domain.com/api/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 208   
```

**Comment by kstkn** [comment]
В чем ваш вопрос? :)

**Comment by ermilov** [comment]
> В чем ваш вопрос? :)

Что с этим делать и от чего это может быть? :)

**Comment by gietos** [comment]
Что с этим делать зависит от того, чего вы хотите достичь. 
Отчего может быть сказано в самом исключении - код, который создает экземпляр класса `Dadata\Client` передает в конструктор неверный аргумент. Нам нужна реализация интерфейса `GuzzleHttp\ClientInterface` из библиотеки https://github.com/guzzle/guzzle а передается экземпляр `Illuminate\Foundation\Application`. Решить проблему можно изменив код таким образом чтобы передавался экземпляр класса реализующего интерфейс `GuzzleHttp\ClientInterface`, например `GuzzleHttp\Client` из той же библиотеки
