### ISSUE TITLE
populateParty: ошибка в правовой форме

### ISSUE THREAD

**Issue by Sky-Cat** [gietos/dadata#48]
Неверно разбирается массив правой формы. Дадата отдает 4 элемента массива, а в коде list() присваивает только три значения:

`list($code, $full, $short) = array_values($response['data']['opf']);`

**Comment by kstkn** [comment]
Thanks for your report, @Sky-Cat 
Fixed in [v1.2.0](https://github.com/kstkn/dadata/releases/tag/v1.2.0)
