### ISSUE TITLE
Пропал Client.php

### ISSUE THREAD

**Issue by Skepolton** [gietos/dadata#51]
Привет! В примере использования указан new Dadata\Client, данного класса нет, new \GuzzleHttp\Client() а GuzzleHttp нету даже в зависимостях

**Comment by Skepolton** [comment]
client.php Так же пропал в версии 1.2 которую использовали (((

**Comment by kstkn** [comment]
Используйте версию 1.1, или официальный клиент https://github.com/hflabs/dadata-php. Этот репозиторий давно не обновляется
